// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpvwlaYQzBaqqJ5p_fzlB1MyGxCQrr71k',
    appId: '1:317451971213:web:58ef6547ff6051d19750c4',
    messagingSenderId: '317451971213',
    projectId: 'flutter-c95e7',
    authDomain: 'flutter-c95e7.firebaseapp.com',
    storageBucket: 'flutter-c95e7.appspot.com',
    measurementId: 'G-KHG3C7MJHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWb7Jhpi1NoVwF98GVt-3O8TWOMdbLS0M',
    appId: '1:317451971213:android:8d8ac657756553649750c4',
    messagingSenderId: '317451971213',
    projectId: 'flutter-c95e7',
    storageBucket: 'flutter-c95e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATAPLuLrAJArQnjhT-1vXhYxLQ9CGbeH0',
    appId: '1:317451971213:ios:e2f00261f8d36e519750c4',
    messagingSenderId: '317451971213',
    projectId: 'flutter-c95e7',
    storageBucket: 'flutter-c95e7.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATAPLuLrAJArQnjhT-1vXhYxLQ9CGbeH0',
    appId: '1:317451971213:ios:fe10c82d4c18a5ae9750c4',
    messagingSenderId: '317451971213',
    projectId: 'flutter-c95e7',
    storageBucket: 'flutter-c95e7.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
